version: "3"
services:
  app:
    build: .
    volumes:
      - /mnt/spinner/scratchprogrammingassets:/assets
    environment:
      - ASSET_DIRECTORY=/assets
    ports:
      - 3333:3333
    restart: always
